export const competencies = [
    '1.1 Placeholder Competency for Neurophysiology 1',
    '1.2 Placeholder Competency for Neurophysiology 2',
    '1.3 Placeholder Competency for Neurophysiology 3',
    '1.4 Placeholder Competency for Neurophysiology 4',
    '1.5 Placeholder Competency for Neurophysiology 5',
    '1.6 Placeholder Competency for Neurophysiology 6',
    '1.7 Placeholder Competency for Neurophysiology 7',
    '1.8 Placeholder Competency for Neurophysiology 8',
    '1.9 Placeholder Competency for Neurophysiology 9',
    '1.10 Placeholder Competency for Neurophysiology 10',
    '1.11 Placeholder Competency for Neurophysiology 11',
    '1.12 Placeholder Competency for Neurophysiology 12',
    '1.13 Placeholder Competency for Neurophysiology 13',
    '1.14 Placeholder Competency for Neurophysiology 14',
    '1.15 Placeholder Competency for Neurophysiology 15',
    '1.16 Placeholder Competency for Neurophysiology 16',
    '1.17 Placeholder Competency for Neurophysiology 17',
    '1.18 Placeholder Competency for Neurophysiology 18',
  ];
  
  export const content = {
    '1.1': {
      'Textbook': [{ title: "Placeholder Textbook", link: "https://example.com" }],
      'Table/Figure': [{ title: "Placeholder Table/Figure", link: "https://example.com" }],
      'Multimedia': [{ title: "Placeholder Multimedia", link: "https://example.com" }],
      'Cases': [{ title: "Placeholder Case", link: "https://example.com" }],
      'Flashcards': [{ title: "Placeholder Flashcard", link: "https://example.com" }],
      'Q & A': [{ title: "Placeholder Q & A", link: "https://example.com" }],
    },
    // Repeat for 1.2 to 1.18 with placeholders
    '1.2': { /* Same as 1.1 */ },
    '1.3': { /* Same as 1.1 */ },
    '1.4': { /* Same as 1.1 */ },
    '1.5': { /* Same as 1.1 */ },
    '1.6': { /* Same as 1.1 */ },
    '1.7': { /* Same as 1.1 */ },
    '1.8': { /* Same as 1.1 */ },
    '1.9': { /* Same as 1.1 */ },
    '1.10': { /* Same as 1.1 */ },
    '1.11': { /* Same as 1.1 */ },
    '1.12': { /* Same as 1.1 */ },
    '1.13': { /* Same as 1.1 */ },
    '1.14': { /* Same as 1.1 */ },
    '1.15': { /* Same as 1.1 */ },
    '1.16': { /* Same as 1.1 */ },
    '1.17': { /* Same as 1.1 */ },
    '1.18': { /* Same as 1.1 */ },
  };